version: '3.8'

services:
  mysql-prod:
    image: mysql:8.0
    container_name: mysql-prod
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: cep_database
    ports:
      - "3307:3306"  # Porta diferente para não conflitar
    volumes:
      - mysql_prod_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - cep-prod-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  cep-api-prod:
    build: .
    container_name: cep-api-prod
    ports:
      - "8081:8080"  # Porta diferente para não conflitar
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: mysql-prod
      DB_PORT: 3306
      DB_NAME: cep_database
      DB_USERNAME: root
      DB_PASSWORD: root123
      VIACEP_API_URL: https://viacep.com.br/ws
    depends_on:
      mysql-prod:
        condition: service_healthy
    networks:
      - cep-prod-network

  adminer-prod:
    image: adminer
    container_name: adminer-prod
    ports:
      - "8082:8080"  # Porta diferente para não conflitar
    networks:
      - cep-prod-network

networks:
  cep-prod-network:
    driver: bridge

volumes:
  mysql_prod_data: