version: '3.8'

services:
  # Banco MySQL
  mysql:
    image: mysql:8.0
    container_name: desafio-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: desafio_cep
      MYSQL_USER: cepuser
      MYSQL_PASSWORD: ceppass123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - app-network

  # Mock da API ViaCEP usando WireMock
  wiremock:
    image: wiremock/wiremock:3.3.1
    container_name: desafio-wiremock
    ports:
      - "8089:8080"
    volumes:
      - ./wiremock/__files:/home/wiremock/__files:ro
      - ./wiremock/mappings:/home/wiremock/mappings:ro
    command: ["--global-response-templating", "--verbose", "--port", "8080"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/__admin/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

  # Aplicação Principal
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: desafio-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - APP_VIACEP_URL=http://wiremock:8080
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/desafio_cep?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=cepuser
      - SPRING_DATASOURCE_PASSWORD=ceppass123
    depends_on:
      mysql:
        condition: service_healthy
      wiremock:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network

  # Adminer (Interface web para gerenciar MySQL)
  adminer:
    image: adminer:4.8.1
    container_name: desafio-adminer
    ports:
      - "8082:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    depends_on:
      - mysql
    networks:
      - app-network

volumes:
  mysql_data:
    driver: local

networks:
  app-network:
    driver: bridge